import 'package:flutter_test/flutter_test.dart';
import 'package:gallery/pages_registry.dart';

const expectedTitles = <String>[
  'ActionIcon',
  'ActionIconGroup',
  'Button',
  'ButtonGroup',
  'CloseButton',
  'CopyButton',
  'FileButton',
  'UnstyledButton',
  'Autocomplete',
  'Cascader',
  'Combobox',
  'ComboboxPopover',
  'MultiSelect',
  'Pill',
  'PillsInput',
  'Select',
  'TagsInput',
  'TreeSelect',
  'Accordion',
  'AccordionItem',
  'Avatar',
  'AvatarGroup',
  'BackgroundImage',
  'Badge',
  'MCard',
  'CardSection',
  'MColorSwatch',
  'DataList',
  'DataListItem',
  'DataListItemLabel',
  'DataListItemValue',
  'MImage',
  'Indicator',
  'Kbd',
  'NumberFormatter',
  'OverflowList',
  'RollingNumber',
  'Spoiler',
  'ThemeIcon',
  'Timeline',
  'TimelineItem',
  'Alert',
  'EmptyState',
  'Loader',
  'Notification',
  'Progress',
  'RingProgress',
  'SemiCircleProgress',
  'Skeleton',
  'AlphaSlider',
  'AngleSlider',
  'Checkbox',
  'CheckboxGroup',
  'Chip',
  'ChipGroup',
  'ColorInput',
  'ColorPicker',
  'Fieldset',
  'FileInput',
  'HueSlider',
  'Input',
  'InputWrapper',
  'JsonInput',
  'MaskInput',
  'NativeSelect',
  'NumberInput',
  'PasswordInput',
  'PinInput',
  'Radio',
  'RadioGroup',
  'RangeSlider',
  'Rating',
  'SegmentedControl',
  'Slider',
  'Switch',
  'SwitchGroup',
  'TextInput',
  'Textarea',
  'AppShell',
  'MAspectRatio',
  'MCenter',
  'MContainer',
  'MFlex',
  'Grid',
  'GridCol',
  'Group',
  'SimpleGrid',
  'Space',
  'Splitter',
  'SplitterPane',
  'MStack',
  'Anchor',
  'Breadcrumbs',
  'Burger',
  'NavLink',
  'Pagination',
  'Stepper',
  'TableOfContents',
  'Tabs',
  'Tree',
  'Affix',
  'Dialog',
  'Drawer',
  'FloatingIndicator',
  'FloatingWindow',
  'HoverCard',
  'LoadingOverlay',
  'Menu',
  'Menubar',
  'Modal',
  'Overlay',
  'Popover',
  'Tooltip',
  'Box',
  'Collapse',
  'Divider',
  'FocusTrap',
  'Marquee',
  'Paper',
  'Portal',
  'ScrollArea',
  'Scroller',
  'MTransition',
  'VisuallyHidden',
  'Blockquote',
  'Code',
  'Highlight',
  'MList',
  'Mark',
  'MTable',
  'MText',
  'MTitle',
  'Typography',
];

void main() {
  test('catalog covers every gallery widget once', () {
    final titles = [for (final page in galleryPages) page.title];
    final uniqueTitles = {for (final page in galleryPages) page.title};
    final uniqueSlugs = {for (final page in galleryPages) page.slug};
    expect(uniqueTitles.length, titles.length);
    expect(uniqueSlugs.length, galleryPages.length);
    expect(titles, expectedTitles);
    for (final page in galleryPages) {
      expect(page.demos, isNotEmpty, reason: page.slug);
    }
  });
}
