name: mantle_core_example
description: Tiny MantleTheme / MantleProvider example.
publish_to: none
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.12.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  mantle_core: ^1.0.0

dev_dependencies:
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: false
