import 'package:flutter/widgets.dart';
import 'package:mantle_basic/src/tokens/basic_colors.dart';
import 'package:mantle_basic/src/tokens/basic_tokens.dart';
import 'package:mantle_basic/src/widgets/buttons/buttons.dart';
import 'package:mantle_basic/src/widgets/combobox/comboboxes.dart';
import 'package:mantle_basic/src/widgets/data_display/data_display.dart';
import 'package:mantle_basic/src/widgets/feedback/feedback.dart';
import 'package:mantle_basic/src/widgets/inputs/inputs.dart';
import 'package:mantle_basic/src/widgets/layout/layout.dart';
import 'package:mantle_basic/src/widgets/miscellaneous/miscellaneous.dart';
import 'package:mantle_basic/src/widgets/navigation/navigation.dart';
import 'package:mantle_basic/src/widgets/overlays/overlays.dart';
import 'package:mantle_basic/src/widgets/typography/typography_widgets.dart';

import 'package:mantle_core/mantle_core.dart';
import 'package:mantle_widgets/mantle_widgets.dart';

/// Baseline theme: Mantine default tokens and component delegates.
///
/// Apps wrap with `MantleProvider(theme: BasicTheme(), child: ...)` so
/// every contract has a terminal implementation.
class BasicTheme extends MantleTheme {
  /// Creates the baseline theme.
  ///
  /// Omitted token groups use Mantine defaults. [components] is merged over
  /// the baseline registry so callers can replace individual delegates.
  // The explicit `super()` call applies Mantine defaults; super-parameters
  // cannot be mixed with that invocation.
  // ignore: use_super_parameters - explicit super() supplies token defaults
  BasicTheme({
    MantleColors? colors,
    MantleIcons? icons,
    MantleTypography? typography,
    MantleSpacing? spacing,
    MantleRadius? radius,
    MantleShadow? shadows,
    MantleBreakpoint? breakpoints,
    DelegateRegistry? components,
    ComponentDefaults? componentDefaults,
    Map<Type, MantleTokenGroup>? extensions,
    String? debugName,
    String? primaryColor,
    MantleShade? primaryShade,
    MantleSize? defaultRadius,
    MantleGradient? defaultGradient,
    MantleFocusRing? focusRing,
    double? scale,
    Color? white,
    Color? black,
    bool? autoContrast,
    double? luminanceThreshold,
    bool? respectReducedMotion,
    MantleCursorType? cursorType,
    VariantColorsResolver? variantColorResolver,
  }) : super(
         debugName: debugName ?? 'BasicTheme',
         colors: colors ?? basicColors,
         icons: icons ?? const MantleIcons.empty(),
         typography: typography ?? basicTypography,
         spacing: spacing ?? basicSpacing,
         radius: radius ?? basicRadius,
         shadows: shadows ?? const MantleShadow.empty(),
         breakpoints: breakpoints ?? basicBreakpoints,
         componentDefaults:
             componentDefaults ?? const ComponentDefaults.empty(),
         extensions: extensions ?? const {},
         primaryColor: primaryColor ?? 'blue',
         primaryShade: primaryShade,
         defaultRadius: defaultRadius ?? 'sm',
         defaultGradient:
             defaultGradient ?? const MantleGradient(from: 'blue', to: 'cyan'),
         focusRing: focusRing,
         scale: scale,
         white: white,
         black: black,
         autoContrast: autoContrast,
         luminanceThreshold: luminanceThreshold,
         respectReducedMotion: respectReducedMotion,
         cursorType: cursorType,
         variantColorResolver: variantColorResolver,
         components: (components ?? const DelegateRegistry.empty()).mergeWith(
           const DelegateRegistry({
             ButtonDelegate: BasicButtonDelegate(),
             ButtonGroupDelegate: BasicButtonGroupDelegate(),
             UnstyledButtonDelegate: BasicUnstyledButtonDelegate(),
             ActionIconDelegate: BasicActionIconDelegate(),
             ActionIconGroupDelegate: BasicActionIconGroupDelegate(),
             CloseButtonDelegate: BasicCloseButtonDelegate(),
             CopyButtonDelegate: BasicCopyButtonDelegate(),
             FileButtonDelegate: BasicFileButtonDelegate(),
             SpaceDelegate: BasicSpaceDelegate(),
             MCenterDelegate: BasicMCenterDelegate(),
             MAspectRatioDelegate: BasicMAspectRatioDelegate(),
             MContainerDelegate: BasicMContainerDelegate(),
             MStackDelegate: BasicMStackDelegate(),
             GroupDelegate: BasicGroupDelegate(),
             MFlexDelegate: BasicMFlexDelegate(),
             SimpleGridDelegate: BasicSimpleGridDelegate(),
             GridDelegate: BasicGridDelegate(),
             GridColDelegate: BasicGridColDelegate(),
             AppShellDelegate: BasicAppShellDelegate(),
             AppShellHeaderDelegate: BasicAppShellHeaderDelegate(),
             AppShellNavbarDelegate: BasicAppShellNavbarDelegate(),
             AppShellAsideDelegate: BasicAppShellAsideDelegate(),
             AppShellFooterDelegate: BasicAppShellFooterDelegate(),
             AppShellMainDelegate: BasicAppShellMainDelegate(),
             AppShellSectionDelegate: BasicAppShellSectionDelegate(),
             SplitterDelegate: BasicSplitterDelegate(),
             SplitterPaneDelegate: BasicSplitterPaneDelegate(),
             AnchorDelegate: BasicAnchorDelegate(),
             BreadcrumbsDelegate: BasicBreadcrumbsDelegate(),
             BurgerDelegate: BasicBurgerDelegate(),
             NavLinkDelegate: BasicNavLinkDelegate(),
             PaginationDelegate: BasicPaginationDelegate(),
             PaginationControlDelegate: BasicPaginationControlDelegate(),
             StepperDelegate: BasicStepperDelegate(),
             StepperStepDelegate: BasicStepperStepDelegate(),
             StepperCompletedDelegate: BasicStepperCompletedDelegate(),
             TableOfContentsDelegate: BasicTableOfContentsDelegate(),
             TabsDelegate: BasicTabsDelegate(),
             TabsListDelegate: BasicTabsListDelegate(),
             TabsTabDelegate: BasicTabsTabDelegate(),
             TabsPanelDelegate: BasicTabsPanelDelegate(),
             TreeDelegate: BasicTreeDelegate(),
             TreeNodeDelegate: BasicTreeNodeDelegate(),
             InputDelegate: BasicInputDelegate(),
             InputWrapperDelegate: BasicInputWrapperDelegate(),
             TextInputDelegate: BasicTextInputDelegate(),
             TextareaDelegate: BasicTextareaDelegate(),
             PasswordInputDelegate: BasicPasswordInputDelegate(),
             NumberInputDelegate: BasicNumberInputDelegate(),
             JsonInputDelegate: BasicJsonInputDelegate(),
             MaskInputDelegate: BasicMaskInputDelegate(),
             FileInputDelegate: BasicFileInputDelegate(),
             NativeSelectDelegate: BasicNativeSelectDelegate(),
             PinInputDelegate: BasicPinInputDelegate(),
             CheckboxDelegate: BasicCheckboxDelegate(),
             CheckboxGroupDelegate: BasicCheckboxGroupDelegate(),
             SwitchDelegate: BasicSwitchDelegate(),
             SwitchGroupDelegate: BasicSwitchGroupDelegate(),
             RadioDelegate: BasicRadioDelegate(),
             RadioGroupDelegate: BasicRadioGroupDelegate(),
             ChipDelegate: BasicChipDelegate(),
             ChipGroupDelegate: BasicChipGroupDelegate(),
             SliderDelegate: BasicSliderDelegate(),
             RangeSliderDelegate: BasicRangeSliderDelegate(),
             RatingDelegate: BasicRatingDelegate(),
             SegmentedControlDelegate: BasicSegmentedControlDelegate(),
             FieldsetDelegate: BasicFieldsetDelegate(),
             ColorPickerDelegate: BasicColorPickerDelegate(),
             ColorInputDelegate: BasicColorInputDelegate(),
             HueSliderDelegate: BasicHueSliderDelegate(),
             AlphaSliderDelegate: BasicAlphaSliderDelegate(),
             AngleSliderDelegate: BasicAngleSliderDelegate(),
             AffixDelegate: BasicAffixDelegate(),
             MOverlayDelegate: BasicMOverlayDelegate(),
             LoadingOverlayDelegate: BasicLoadingOverlayDelegate(),
             TooltipDelegate: BasicTooltipDelegate(),
             DialogDelegate: BasicDialogDelegate(),
             ModalDelegate: BasicModalDelegate(),
             ModalRootDelegate: BasicModalRootDelegate(),
             DrawerDelegate: BasicDrawerDelegate(),
             PopoverDelegate: BasicPopoverDelegate(),
             PopoverTargetDelegate: BasicPopoverTargetDelegate(),
             PopoverDropdownDelegate: BasicPopoverDropdownDelegate(),
             HoverCardDelegate: BasicHoverCardDelegate(),
             HoverCardTargetDelegate: BasicHoverCardTargetDelegate(),
             HoverCardDropdownDelegate: BasicHoverCardDropdownDelegate(),
             MenuDelegate: BasicMenuDelegate(),
             MenuTargetDelegate: BasicMenuTargetDelegate(),
             MenuDropdownDelegate: BasicMenuDropdownDelegate(),
             MenuItemDelegate: BasicMenuItemDelegate(),
             MenuLabelDelegate: BasicMenuLabelDelegate(),
             MenuDividerDelegate: BasicMenuDividerDelegate(),
             MenubarDelegate: BasicMenubarDelegate(),
             MenubarMenuDelegate: BasicMenubarMenuDelegate(),
             MenubarTargetDelegate: BasicMenubarTargetDelegate(),
             MenubarDropdownDelegate: BasicMenubarDropdownDelegate(),
             FloatingIndicatorDelegate: BasicFloatingIndicatorDelegate(),
             FloatingWindowDelegate: BasicFloatingWindowDelegate(),
             KbdDelegate: BasicKbdDelegate(),
             MColorSwatchDelegate: BasicMColorSwatchDelegate(),
             ThemeIconDelegate: BasicThemeIconDelegate(),
             NumberFormatterDelegate: BasicNumberFormatterDelegate(),
             BadgeDelegate: BasicBadgeDelegate(),
             AvatarDelegate: BasicAvatarDelegate(),
             AvatarGroupDelegate: BasicAvatarGroupDelegate(),
             MImageDelegate: BasicMImageDelegate(),
             BackgroundImageDelegate: BasicBackgroundImageDelegate(),
             IndicatorDelegate: BasicIndicatorDelegate(),
             MCardDelegate: BasicMCardDelegate(),
             CardSectionDelegate: BasicCardSectionDelegate(),
             AccordionDelegate: BasicAccordionDelegate(),
             AccordionItemDelegate: BasicAccordionItemDelegate(),
             SpoilerDelegate: BasicSpoilerDelegate(),
             TimelineDelegate: BasicTimelineDelegate(),
             TimelineItemDelegate: BasicTimelineItemDelegate(),
             DataListDelegate: BasicDataListDelegate(),
             DataListItemDelegate: BasicDataListItemDelegate(),
             DataListItemLabelDelegate: BasicDataListItemLabelDelegate(),
             DataListItemValueDelegate: BasicDataListItemValueDelegate(),
             OverflowListDelegate: BasicOverflowListDelegate(),
             RollingNumberDelegate: BasicRollingNumberDelegate(),
             AlertDelegate: BasicAlertDelegate(),
             EmptyStateDelegate: BasicEmptyStateDelegate(),
             LoaderDelegate: BasicLoaderDelegate(),
             MNotificationDelegate: BasicMNotificationDelegate(),
             ProgressDelegate: BasicProgressDelegate(),
             RingProgressDelegate: BasicRingProgressDelegate(),
             SemiCircleProgressDelegate: BasicSemiCircleProgressDelegate(),
             SkeletonDelegate: BasicSkeletonDelegate(),
             ComboboxDelegate: BasicComboboxDelegate(),
             ComboboxTargetDelegate: BasicComboboxTargetDelegate(),
             ComboboxDropdownDelegate: BasicComboboxDropdownDelegate(),
             ComboboxOptionsDelegate: BasicComboboxOptionsDelegate(),
             ComboboxOptionDelegate: BasicComboboxOptionDelegate(),
             ComboboxGroupDelegate: BasicComboboxGroupDelegate(),
             ComboboxEmptyDelegate: BasicComboboxEmptyDelegate(),
             ComboboxSearchDelegate: BasicComboboxSearchDelegate(),
             ComboboxChevronDelegate: BasicComboboxChevronDelegate(),
             ComboboxHeaderDelegate: BasicComboboxHeaderDelegate(),
             ComboboxFooterDelegate: BasicComboboxFooterDelegate(),
             ComboboxPopoverDelegate: BasicComboboxPopoverDelegate(),
             ComboboxPopoverTargetDelegate:
                 BasicComboboxPopoverTargetDelegate(),
             SelectDelegate: BasicSelectDelegate(),
             MultiSelectDelegate: BasicMultiSelectDelegate(),
             AutocompleteDelegate: BasicAutocompleteDelegate(),
             TagsInputDelegate: BasicTagsInputDelegate(),
             PillDelegate: BasicPillDelegate(),
             PillGroupDelegate: BasicPillGroupDelegate(),
             PillsInputDelegate: BasicPillsInputDelegate(),
             PillsInputFieldDelegate: BasicPillsInputFieldDelegate(),
             CascaderDelegate: BasicCascaderDelegate(),
             TreeSelectDelegate: BasicTreeSelectDelegate(),
             BoxDelegate: BasicBoxDelegate(),
             CollapseDelegate: BasicCollapseDelegate(),
             DividerDelegate: BasicDividerDelegate(),
             FocusTrapDelegate: BasicFocusTrapDelegate(),
             MarqueeDelegate: BasicMarqueeDelegate(),
             PaperDelegate: BasicPaperDelegate(),
             PortalDelegate: BasicPortalDelegate(),
             ScrollAreaDelegate: BasicScrollAreaDelegate(),
             ScrollerDelegate: BasicScrollerDelegate(),
             MTransitionDelegate: BasicMTransitionDelegate(),
             VisuallyHiddenDelegate: BasicVisuallyHiddenDelegate(),
             MTextDelegate: BasicMTextDelegate(),
             MTitleDelegate: BasicMTitleDelegate(),
             CodeDelegate: BasicCodeDelegate(),
             MarkDelegate: BasicMarkDelegate(),
             HighlightDelegate: BasicHighlightDelegate(),
             BlockquoteDelegate: BasicBlockquoteDelegate(),
             MListDelegate: BasicMListDelegate(),
             ListItemDelegate: BasicListItemDelegate(),
             MTableDelegate: BasicMTableDelegate(),
             TableTheadDelegate: BasicTableTheadDelegate(),
             TableTbodyDelegate: BasicTableTbodyDelegate(),
             TableTfootDelegate: BasicTableTfootDelegate(),
             TableTrDelegate: BasicTableTrDelegate(),
             TableThDelegate: BasicTableThDelegate(),
             TableTdDelegate: BasicTableTdDelegate(),
             TableCaptionDelegate: BasicTableCaptionDelegate(),
             TableScrollContainerDelegate:
                 BasicTableScrollContainerDelegate(),
             TypographyDelegate: BasicTypographyDelegate(),
           }),

         ),
       );
}
